import type { Config } from 'tailwindcss';

const config: Config = {
    content: [
        './app/**/*.{js,ts,jsx,tsx,mdx}',
        './components/**/*.{js,ts,jsx,tsx,mdx}',
    ],
    theme: {
        extend: {
            colors: {
                surface: '#f8f9ff',
                'surface-dim': '#cbdbf5',
                'surface-bright': '#f8f9ff',
                'surface-container-lowest': '#ffffff',
                'surface-container-low': '#eff4ff',
                'surface-container': '#e5eeff',
                'surface-container-high': '#dce9ff',
                'surface-container-highest': '#d3e4fe',
                'on-surface': '#0b1c30',
                'on-surface-variant': '#434655',
                'inverse-surface': '#213145',
                'inverse-on-surface': '#eaf1ff',
                outline: '#737686',
                'outline-variant': '#c3c6d7',
                'surface-tint': '#0053db',
                primary: {
                    DEFAULT: '#004ac6',
                    container: '#2563eb',
                },
                'on-primary': '#ffffff',
                'on-primary-container': '#eeefff',
                'inverse-primary': '#b4c5ff',
                secondary: '#565e74',
                'on-secondary': '#ffffff',
                'secondary-container': '#dae2fd',
                'on-secondary-container': '#5c647a',
                tertiary: '#8e3c00',
                'on-tertiary': '#ffffff',
                'tertiary-container': '#b54e00',
                'on-tertiary-container': '#ffece5',
                error: '#ba1a1a',
                'on-error': '#ffffff',
                'error-container': '#ffdad6',
                'on-error-container': '#93000a',
                'primary-fixed': '#dbe1ff',
                'primary-fixed-dim': '#b4c5ff',
                'on-primary-fixed': '#00174b',
                'on-primary-fixed-variant': '#003ea8',
                'secondary-fixed': '#dae2fd',
                'secondary-fixed-dim': '#bec6e0',
                'on-secondary-fixed': '#131b2e',
                'on-secondary-fixed-variant': '#3f465c',
                'tertiary-fixed': '#ffdbca',
                'tertiary-fixed-dim': '#ffb690',
                'on-tertiary-fixed': '#341100',
                'on-tertiary-fixed-variant': '#783200',
                background: '#f8f9ff',
                'on-background': '#0b1c30',
                'surface-variant': '#d3e4fe',
                orange: '#F97316',
                success: '#10b981',
                warning: '#f59e0b',
            },
            fontFamily: {
                inter: ['Inter', 'sans-serif'],
            },
            fontSize: {
                'display-lg': ['48px', { lineHeight: '56px', fontWeight: '700', letterSpacing: '-0.02em' }],
                'headline-lg': ['32px', { lineHeight: '40px', fontWeight: '700', letterSpacing: '-0.01em' }],
                'headline-lg-mobile': ['28px', { lineHeight: '36px', fontWeight: '700' }],
                'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
                'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
                'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
                'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
                'label-md': ['14px', { lineHeight: '20px', fontWeight: '600', letterSpacing: '0.05em' }],
                'spec-code': ['13px', { lineHeight: '18px', fontWeight: '500' }],
            },
            spacing: {
                xs: '8px',
                sm: '16px',
                md: '24px',
                lg: '40px',
                xl: '64px',
            },
            borderRadius: {
                sm: '4px',
                DEFAULT: '8px',
                md: '12px',
                lg: '16px',
                xl: '24px',
                full: '9999px',
            },
            maxWidth: {
                container: '1280px',
            },
            gap: {
                gutter: '24px',
            },
            boxShadow: {
                'level-1': '0 1px 3px rgba(0, 0, 0, 0.04)',
                'level-2': '0 4px 8px rgba(0, 0, 0, 0.08)',
                'level-3': '0 12px 24px rgba(0, 0, 0, 0.16)',
            },
        },
    },
    plugins: [],
};

export default config;